import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Challenge from './models/Challenge.js';
import Submission from './models/Submission.js';
import User from './models/User.js';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import auth from './middleware/auth.js';
import Classroom from './models/Classroom.js';
import upload from './middleware/upload.js'


dotenv.config();
//the above line allows us to read variables in .env file and load them into the process.env object for use in our code

const app=express();

// Add both your local dev environment AND your live Vercel production URL
const allowedOrigins = [
    'http://localhost:5173', 
    'https://gamified-platform-ok56.vercel.app'
];

app.use(cors({
    origin: function (origin, callback) {
        // Allow requests with no origin (like mobile apps or curl requests)
        if (!origin) return callback(null, true);
        
        if (allowedOrigins.indexOf(origin) === -1) {
            const msg = 'The CORS policy for this site does not allow access from the specified Origin.';
            return callback(new Error(msg), false);
        }
        return callback(null, true);
    },
    credentials: true
}));
//the above middleware allows our frontend and backend which are on different ports to communicate to one another without the browser blocking the connection due to CORS


app.use(express.json());

//Database connection below
console.log("DEBUG - My URI is:", `[${process.env.MONGO_URI}]`);
mongoose.connect(process.env.MONGO_URI).then(()=>console.log('MongoDB successfully connected!')).catch((err)=>console.log('MongoDB connection error:',err))

// 1. CREATE A CHALLENGE FOR A SPECIFIC CLASSROOM (PROFESSOR ONLY)
app.post('/api/classrooms/:classroomId/challenges', auth, async (req, res) => {
    try {
        // Role check
        if (req.user.role !== 'professor') {
            return res.status(403).json({ error: 'Access denied. Only professors can create challenges.' });
        }

        const { title, description, points } = req.body;
        const { classroomId } = req.params;

        // Build the challenge securely tied to the classroom parameter
        const newChallenge = new Challenge({
            title,
            description,
            points: points || 10,
            classroom: classroomId
        });

        await newChallenge.save();
        res.status(201).json(newChallenge);
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to create challenge!' });
    }
});

// 2. GET ALL CHALLENGES LOCKED TO A SPECIFIC CLASSROOM
app.get('/api/classrooms/:classroomId/challenges', auth, async (req, res) => {
    try {
        const { classroomId } = req.params;

        // Only pull challenges that match this specific classroom ID
        const challenges = await Challenge.find({ classroom: classroomId })
            .sort({ createdAt: -1 });

        res.status(200).json(challenges);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'No challenges active at the moment!' });
    }
});
//for students to submit a challenge
app.post('/api/challenges/:challengeId/submit',auth,upload.single('mediaFile'),async(req,res)=>{
  
  try{
    if(req.user.role!=='student'){
        return res.status(403).json({error:'Access denied. Students only.'})
    }

    const{challengeId}=req.params;
    const{comment}=req.body ||{};
    //the below line allows for determining if we are uploading a file  
    //so cloudinary gives us a path  represents the full temporary or permanent location where an uploaded 
    // file is saved on your server. It is generated by the popular Multer middleware during a multipart/form-data upload or 
    // if we give a github link it will be in req.body
    const finalUrl = req.file ? req.file.path : (req.body ? req.body.submissionUrl : null);

    if(!finalUrl){
        return res.status(400).json({error:'Submission link or file is required'})

    }

    const challenge =await Challenge.findById(challengeId);
    if(!challenge){
        return res.status(404).json({error:'Challenge not found!'})
    }
    const existingSubmission=await Submission.findOne({
        challenge:challengeId,
        student:req.user.id
    })

    if(existingSubmission){
        return res.status(400).json({ error: 'You have already submitted for this challenge!' })
    }
   const newSubmission = new Submission({
            challenge: challengeId,
            student: req.user.id,
            submissionUrl:finalUrl,
            comment,
            status: 'pending' // pending, approved, rejected
        });

        await newSubmission.save();

        res.status(201).json({ 
            message: 'Challenge submitted successfully!', 
            submission: newSubmission 
        });
}
catch(error){
    console.error(error)
    res.status(500).json({message:'Submission failed!'})
}
})
// GET PENDING SUBMISSIONS FOR A PROFESSOR'S CLASSROOMS
app.get('/api/submissions/pending', auth, async (req, res) => {
    try {
        if (req.user.role !== 'professor') {
            return res.status(403).json({ error: 'Access denied. Professors only.' });
        }

        // 1. Find all classrooms owned by this professor
        const classrooms = await Classroom.find({ professor: req.user.id });
        const classroomIds = classrooms.map(c => c._id);

        // 2. Find challenges linked to those classrooms
        const challenges = await Challenge.find({ classroom: { $in: classroomIds } });
        const challengeIds = challenges.map(ch => ch._id);

        // 3. Get pending submissions for those challenges, populated with Student & Challenge data
        const pendingSubmissions = await Submission.find({
            challenge: { $in: challengeIds },
            status: 'pending'
        })
        .populate('student', 'name email')
        .populate('challenge', 'title points');

        res.status(200).json(pendingSubmissions);
    } catch (error) {
        console.error("Fetch pending error:", error);
        res.status(500).json({ error: 'Failed to fetch grading queue.' });
    }
});

// APPROVE A SUBMISSION & AWARD XP
app.post('/api/submissions/:submissionId/approve', auth, async (req, res) => {
    try {
        if (req.user.role !== 'professor') {
            return res.status(403).json({ error: 'Access denied. Professors only.' });
        }

        // 1. Find the submission and explicitly pull in the challenge data
        const submission = await Submission.findById(req.params.submissionId).populate('challenge');
        
        if (!submission) {
            return res.status(404).json({ error: 'Submission not found.' });
        }
        if (submission.status !== 'pending') {
            return res.status(400).json({ error: 'This submission has already been graded.' });
        }

        // 2. Award the points and change the status
        submission.status = 'approved';
        submission.pointsAwarded = submission.challenge.points; 
        
        await submission.save();

        res.status(200).json({ 
            message: `Successfully awarded ${submission.pointsAwarded} XP!`,
            submission 
        });
    } catch (error) {
        console.error("Grading error:", error);
        res.status(500).json({ error: 'Failed to approve submission.' });
    }
});

app.post('/api/auth/register',async (req,res)=>{
    try{
        const{name,email,password,role}=req.body;
        const existingUser=await User.findOne({email});
        if(existingUser){
            return res.status(400).json({error:'Email is already registered!'})
        }
        //encrypting the password!!
        const salt=await bcrypt.genSalt(10);
        const hashedPassword=await bcrypt.hash(password,salt);

        //create user with new hashed password!
        const newUser=new User({
            name,
            email,
            password:hashedPassword,
            role:role || 'student'
        })
        await newUser.save();
        res.status(201).json({message:'user registered successfully!'})
    }catch(error){
        console.error('registration error',error);
        res.status(500).json({error:'Server error during registration!'})
    }
})
//login the user
app.post('/api/auth/login',async(req,res)=>{
    try{
        const{email,password}=req.body;

        const user=await User.findOne({email});
        if(!user){
            return res.status(400).json({error:'Invalid email or password!'})
        }
        const isMatch=await bcrypt.compare(password,user.password)
        if(!isMatch){
            return res.status(400).json({error:'Invalid email or password!'})
        }
        //generating the JWT
        const token=jwt.sign({id:user._id,role:user.role},process.env.JWT_SECRET,{expiresIn:'1d'})
        res.status(200).json({
            token,
            user:{
                id:user._id,
                name:user.name,
                role:user.role,
                xp:user.xp
            }
        })    
    }catch(error){
        console.error('login error',error);
        res.status(500).json({error:'Server error during login'})
    }
})
app.post('/api/classrooms/create',auth,async(req,res)=>{
    try{
        if(req.user.role!=='professor'){
            return res.status(403).json("error:Access only given to professors!")
        }
        const{name}=req.body;
        const joinCode=Math.random().toString(36).substring(2,8).toUpperCase();
        const newClassroom=new Classroom({
            name,
            professor:req.user.id,
            joinCode
        })
        await newClassroom.save();
        res.status(201).json({message:'Classroom created',classroom:newClassroom})
    }
    catch(error){
        console.error(error);
        res.status(500).json({error:'Server error while creating classroom!'})
    }

})

app.post('/api/classrooms/join',auth ,async(req,res)=>{
    try{
        if(req.user.role!=='student'){
            return res.status(403).json({error:'Only students can join!'})
        }
        const{joinCode}=req.body;

        const classroom=await Classroom.findOne({joinCode:joinCode.toUpperCase()})
        if(!classroom){
            return res.status(404).json({error:'Classroom not found!!'})
        }
        if(classroom.students.includes(req.user.id)|| classroom.pendingRequests.includes(req.user.id)){
            return res.status(400).json({error:'You are already in this class or have a pending request.'})
        }
        classroom.pendingRequests.push(req.user.id);
        await classroom.save();
        res.status(200).json({message:'Join request sent to professor!'})
    }
    catch(error){
        console.error(error)
            res.status(500).json({error:'Server error while requesting to join!'})
        }
    })

// APPROVE A STUDENT TO JOIN A CLASSROOM
app.post('/api/classrooms/:classroomId/approve', auth, async (req, res) => {
    try {
        if (req.user.role !== 'professor') {
            return res.status(403).json({ error: 'Access denied. Professors only.' });
        }

        const { classroomId } = req.params;
        const { studentId } = req.body;

        const classroom = await Classroom.findById(classroomId);
        if (!classroom) {
            return res.status(404).json({ error: 'Classroom not found.' });
        }

        // SAFE COMPARISON: Convert ObjectId to String using .toString()
        const isPending = classroom.pendingRequests.some(id => id.toString() === studentId);
        
        if (!isPending) {
            return res.status(400).json({ error: 'Student is not in the waiting room.' });
        }

        // 1. Remove from waiting room (filter out strings)
        classroom.pendingRequests = classroom.pendingRequests.filter(
            id => id.toString() !== studentId
        );

        // 2. Add to official student roster if not already there
        if (!classroom.students.map(id => id.toString()).includes(studentId)) {
            classroom.students.push(studentId);
        }

        await classroom.save();
        res.status(200).json({ message: 'Student approved successfully!' });
    } catch (error) {
        console.error("Approval Error:", error);
        res.status(500).json({ error: 'Failed to approve student.' });
    }
});
// GET A PROFESSOR'S CLASSROOMS
app.get('/api/classrooms/me', auth, async (req, res) => {
    try {
        if (req.user.role !== 'professor') {
            return res.status(403).json({ error: 'Access denied.' });
        }
        // Find all classrooms where the professor ID matches the logged-in user
        const classrooms = await Classroom.find({ professor: req.user.id })
              .populate('pendingRequests','name email')
              .populate('students','name email')
        res.status(200).json(classrooms);
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to fetch classrooms' });
    }
});
// GET A STUDENT'S ENROLLED CLASSROOMS
app.get('/api/classrooms/enrolled', auth, async (req, res) => {
    try {
        if (req.user.role !== 'student') {
            return res.status(403).json({ error: 'Access denied. Students only.' });
        }
        
        // Find classes where this user's ID exists in the 'students' array
        const classrooms = await Classroom.find({ students: req.user.id });
        res.status(200).json(classrooms);
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to fetch enrolled classes' });
    }
});
app.get('/api/classrooms/:classroomId/leaderboard',auth,async(req,res)=>{
    try{
        const{classroomId}=req.params;
        //getting all challenges for a particular classroom
        const challenges=await Challenge.find({classroom:classroomId})
        const challengeIds=challenges.map(ch=>ch._id);
        if(challengeIds.length===0){
            return res.status(200).json([]) //no challenges or empty leaderboard
        }

        const leaderboard=await Submission.aggregate([
          //stage 1: look for approved submissions only
          {$match:{challenge:{$in:challengeIds},status:'approved'}},
          //stage 2:group by studentId and sum up their points
          {$group:{_id:'$student',totalXP:{$sum:'$pointsAwarded'}}},
          //stage3: sort by totalXP in descending order
          {$sort:{totalXP:-1}},
          //stage4: fetch student details from Users collection
          {$lookup:{//lookup returns an array hence we need to use unwind to extract the object inside
            from:'users',
            localField:'_id',
            foreignField:'_id',
            as:'studentInfo'
          }},
          //stage5: unpack the array and format the final output
          { $unwind:'$studentInfo'},
          {$project:{
            _id:1,//1 means to keep it 0 means to not keep it
            totalXP:1,
            name:'$studentInfo.name',
            email:'$studentInfo.email'
          }}  
        ])
        res.status(200).json(leaderboard);
    }
    catch (error) {
        console.error("Leaderboard error:", error);
        res.status(500).json({ error: 'Failed to generate leaderboard.' });
    }
})
// GET GLOBAL LEADERBOARD (The Hall of Fame)
app.get('/api/leaderboard/global', auth, async (req, res) => {
    try {
        const globalLeaderboard = await Submission.aggregate([
            // Stage 1: The Bouncer - Only let APPROVED submissions through (from ANY class)
            { $match: { status: 'approved' } },
            
            // Stage 2: The Accountant - Group by student, sum ALL points they've ever earned
            { $group: { _id: '$student', totalXP: { $sum: '$pointsAwarded' } } },
            
            // Stage 3: The Ranker - Sort highest XP to the top
            { $sort: { totalXP: -1 } },
            
            // Stage 4 & 5: The Matchmaker & Unpacker - Attach the student's profile info
            { $lookup: { 
                from: 'users', 
                localField: '_id', 
                foreignField: '_id', 
                as: 'studentInfo' 
            }},
            { $unwind: '$studentInfo' },
            
            // Stage 6: The Cleaner - Format for the frontend
            { $project: { 
                _id: 1, 
                totalXP: 1, 
                name: '$studentInfo.name', 
                email: '$studentInfo.email' 
            }}
        ]);

        res.status(200).json(globalLeaderboard);
    } catch (error) {
        console.error("Global Leaderboard error:", error);
        res.status(500).json({ error: 'Failed to generate global leaderboard.' });
    }
});
const PORT=process.env.PORT || 5000;
app.listen(PORT,()=>{
    console.log(`Server is running on ${PORT}...`)
})


